# Generated by Django 3.2.5 on 2023-01-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.SmallIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='created_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='updated_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='productvariantprice',
            name='created_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='productvariantprice',
            name='updated_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='variant',
            name='created_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='variant',
            name='updated_at',
            field=models.TimeField(),
        ),
    ]
