# Generated by Django 3.2.5 on 2023-01-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230130_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.SmallIntegerField(default=0),
        ),
    ]
